[package]
name = "gray"
version = "0.1.0"
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
image = "0.23"
web-sys = "0.3"

[lib]
crate-type = ["cdylib"]

# [dependencies.wee_alloc]
# version = "0.4"
# default-features = false
# features = ["wee_alloc"]
